#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : scdoc
Version  : 1.9.4
Release  : 3
URL      : https://git.sr.ht/~sircmpwn/scdoc/archive/1.9.4.tar.gz
Source0  : https://git.sr.ht/~sircmpwn/scdoc/archive/1.9.4.tar.gz
Summary  : Man page generator
Group    : Development/Tools
License  : MIT
Requires: scdoc-bin = %{version}-%{release}
Requires: scdoc-license = %{version}-%{release}
Requires: scdoc-man = %{version}-%{release}

%description
# scdoc
scdoc is a simple man page generator for POSIX systems written in C99.
## Installation

%package bin
Summary: bin components for the scdoc package.
Group: Binaries
Requires: scdoc-license = %{version}-%{release}

%description bin
bin components for the scdoc package.


%package dev
Summary: dev components for the scdoc package.
Group: Development
Requires: scdoc-bin = %{version}-%{release}
Provides: scdoc-devel = %{version}-%{release}
Requires: scdoc = %{version}-%{release}

%description dev
dev components for the scdoc package.


%package license
Summary: license components for the scdoc package.
Group: Default

%description license
license components for the scdoc package.


%package man
Summary: man components for the scdoc package.
Group: Default

%description man
man components for the scdoc package.


%prep
%setup -q -n scdoc-1.9.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559681197
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} PREFIX=/usr LDFLAGS="$LDFLAGS"


%install
export SOURCE_DATE_EPOCH=1559681197
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/scdoc
cp COPYING %{buildroot}/usr/share/package-licenses/scdoc/COPYING
%make_install PREFIX=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/scdoc

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/scdoc.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/scdoc/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/scdoc.1
/usr/share/man/man5/scdoc.5
